apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amadeus-global-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: british-airways-booking-service
            port:
              number: 80 # This matches the port exposed by your service.yaml