# Default values for Amadeus Booking Engine.
replicaCount: 3

image:
  repository: <YOUR_ACR_NAME>.azurecr.io/amadeus-flight-api
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8080 # Changed from 80 to 8080 because our Python Flask app runs on 8080!